### ISSUE TITLE
Movie thumbails not showing on favorites view

### ISSUE THREAD

**Issue by barkingdog1914** [popcorntime/popcorntime#193]
Operating System Version: OS X 10.11.5

Popcorn Time Version: 0.3.9 Build 69375736

Download date: I don't remember, sorry

Expected Behaviour: When I open the favourites view I expect to see my favourite movies and series along with their pictures.

Actual Behaviour: Movies are showing but they use a generic picture instead of the proper one. Meanwhile pictures for series are properly shown.

Steps to repoduce the behaviour:
1.Go to the movies view and mark a movie as favourite.
2.Go to the series view and mark a serie as favourite.
3.Go to the favourites view. You will see both the movie and the serie, but the movie has a generic picture.

Note: Similar issue has also been reported here https://github.com/popcorn-official/popcorn-desktop/issues/109 for the Linux Systems.

**Comment by VitorVRS** [comment]
Your PCT application is outdated (from your commit). 
As you mentioned issue #109, this was fixed before.
Try download a more recent version from: popcorntime.sh

**Comment by barkingdog1914** [comment]
Thank you for your answer. I did that and it now works.
The problem is that I don't know how to check for the newest version as the app doesn't have an auto-updater (as far as I am concerned) and the version on the homepage is still the same (0.3.9, only the build is different).
Do you have any clues on how to check for newer versions as long as the build number is not shown on the download page: popcorntime.sh?

**Comment by VitorVRS** [comment]
I understand you, it sucks that PCT doesn't have an autoupdater yet.
We are trying to improve our versionming and re-activate the autoupdater. 
There is already an issue for autoupdating, feel free to contribute (if you want).

**Comment by barkingdog1914** [comment]
Thanx again for the info. Hopefully PCT autoupdater will be soon available.
I'll check the corresponding thread as advised.
Till then is there a page here that includes a list with all the versions so we can check manually which is the latest one?

**Comment by VitorVRS** [comment]
You can look at PCT CI: https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/
But now its kind a mess, since the owner was testing another branch.
Usually each build its an version.
If you more doubts about that its not about development, i suggest you to post on PCT subreddit: https://www.reddit.com/r/PopCornTime/
Maybe there you get more answers from more people.

**Comment by barkingdog1914** [comment]
Thanks again m8.
So hopefully this issue will be solved soon.
Keep up the good work!
Cheers!
