### ISSUE TITLE
Subtitles are not selectable for movies.

### ISSUE THREAD

**Issue by brazucao** [popcorntime/popcorntime#227]
Operating System Version: Windows 10
Popcorn Time Version: 0.3.9 Build #139

Download date: 12092016
#### Expected Behaviour

Subtitle Default Settings selected but not playing automatic in the player, language flags are also absent.

**Comment by Jonnathanjons** [comment]
Hello Subtitle flag is disabled ..not showing even after set up correctly in the settings see the screenshot below. Pls help on this.
![subtitle notshowiginpt](https://cloud.githubusercontent.com/assets/20332723/18543345/f626309e-7b4c-11e6-9953-b78ce445edef.JPG)

**Comment by MenosOcho** [comment]
yeap, subtitles are showing as not available.

**Comment by ChrisAlderson** [comment]
We have removed the dropdown to select a subtitle language. Subtitles can still be selected within the internal player and movies will use the value for default subtitles selected in the settings.

**Comment by carlosnpz** [comment]
Still won't show...

![print1](https://cloud.githubusercontent.com/assets/4489481/19626889/e6bd4332-9919-11e6-9449-dab329008cc3.jpg)
![print2](https://cloud.githubusercontent.com/assets/4489481/19626890/e6c521c4-9919-11e6-9656-7c3bd710c2de.jpg)

**Comment by carlosnpz** [comment]
Also the option "Connect to OpenSubtitles" won't work. I can log in through their website, but not through PopcornTime.

**Comment by ChrisAlderson** [comment]
![subs1](https://cloud.githubusercontent.com/assets/17688012/19627010/145afdba-993e-11e6-9005-80f671e2f961.jpeg)
![subs2](https://cloud.githubusercontent.com/assets/17688012/19627012/14749144-993e-11e6-9c60-63ebb640c5ed.jpeg)
![subs3](https://cloud.githubusercontent.com/assets/17688012/19627011/14744824-993e-11e6-8f0b-706df86b7a28.jpeg)

Both are fixed.

**Comment by carlosnpz** [comment]
Can you post the download link of this version?

**Comment by ChrisAlderson** [comment]
As always ci.popcorntime.sh for the latest sources

**Comment by carlosnpz** [comment]
Really don't know what's happening, but it's still not working... :'(

**Comment by carlosnpz** [comment]
Weird, but now it's working. I selected Portuguese (Brazil), but somehow Popcorn Time deactivated subtitles when I started watching the show. Then I went to settings and activated again, and now it's working! oO

**Comment by ValentinH** [comment]
@ChrisAlderson You wrote "We have removed the dropdown to select a subtitle language." I just want to highlight the fact that we can't choose the subtitles anymore when playing on Chromecast... How are we suppose to do that?
