### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by carlosnpz** [popcorntime/popcorntime#23]
Subtitles are not being loaded in any film or series even if the OpenSubtitles connection is active...

**Comment by pralium444** [comment]
confirmed.. mainly on tv shows.... and external subtitles don't load either

**Comment by pralium444** [comment]
works fine on popcortime CE

**Comment by kim0** [comment]
After all the confusion, I was thinking "here" should be the fork with the most development .. we'll see!

Anyway .. I tried debugging this a bit (I'm in no way qualified) .. AFAICT, popcorn time always uses ysubs.com .. which for some reason is no longer returning results. Examples for the big bang theory
http://api.yifysubtitles.com/subs/tt0898266
http://api.ysubs.com/subs/tt0898266

which both return no results .. Even http://www.ysubs.com/ says it's under maintenance for many days now. It seems ysubs is moving under a new name (http://www.tv-subs.com/) which does indeed have a npm api module (https://www.npmjs.com/package/tv-subs) .. However it seems the api is different than usual! So a solution might include switching to the new tv-subs, or to open-subtitles .. or both .. unless my understanding is wrong .. Anyway, thought to put this here as it might help a developer fix this

**Comment by pralium444** [comment]
or www.addic7ed.com ! would love to see that site included.. but your analysis does not explain the fact that external subtitles won't show when you add them from any  local drive

**Comment by brunobsouzac** [comment]
another old but never solved problem, was able to see television shows in 720p with audio in chromecast or watch 720p movies with subtitles!

And can also select a legend after streaming has begun! The same goes for the Android App.

Strem.io have these options but is popcorn time favorite!

**Comment by team-pct** [comment]
Please try https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/35/ And report us any improvement suggestion

**Comment by kim0** [comment]
@team-pct .. it seems to work now, thanks!! I tried a couple of episodes, seems to work well

**Comment by carlosnpz** [comment]
No deal... The subtitles problem remains the same for me, just as in the image below. Not being loaded, even if I'm connected to Open Subtitles. Don't know what's happening. I've tried lots of movies. :/

![print](https://cloud.githubusercontent.com/assets/4489481/13329355/20e131be-dbd2-11e5-843a-e9733cb3bdde.jpg)

**Comment by kim0** [comment]
@carlosnpz I think try to set your default subtitles choice in settings to some language (English for me) .. I think that helps coz I used to get this empty list before

**Comment by carlosnpz** [comment]
@kim0 Changing language didn't solve the problem for me.

**Comment by team-pct** [comment]
@carlosnpz try to get us logs F12 when you try stream a movie would help a lot

**Comment by Breaking1** [comment]
In the latest build subtitles works fine: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/35/

So for anyone with this problem download the version from here and it should fix any problems with subtitles not showing.

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/35

I couldn't get up anything with f12 on previous builds.

**Comment by carlosnpz** [comment]
@team-pct Is there a way to save the log to send you when I press F12?

**Comment by Breaking1** [comment]
@carlosnpz Take a screenshot of the console log and post it here.

**Comment by carlosnpz** [comment]
Good old way, hahaha. Ok, Here they are:

![log1](https://cloud.githubusercontent.com/assets/4489481/13334633/c1f6c55a-dbeb-11e5-88b7-139feb421bde.jpg)
![log2](https://cloud.githubusercontent.com/assets/4489481/13334635/c2107edc-dbeb-11e5-80c4-ab53a14ca353.jpg)

**Comment by team-pct** [comment]
@carlosnpz Can you go now to settings and take screenshot ?

**Comment by carlosnpz** [comment]
Sorry for being late, @team-pct. I changed some settings before seeing your last message, so I took all the requested screenshots again:
![screen1](https://cloud.githubusercontent.com/assets/4489481/13341822/c0df46f4-dc1a-11e5-80aa-908824a0606d.png)
![screen2](https://cloud.githubusercontent.com/assets/4489481/13341823/c0e350fa-dc1a-11e5-8ae3-6dbad97ac6c3.png)
![screen3](https://cloud.githubusercontent.com/assets/4489481/13341824/c0e3f6ae-dc1a-11e5-8a81-8a33ba42c4dc.png)
![screen4](https://cloud.githubusercontent.com/assets/4489481/13341825/c0ec10b4-dc1a-11e5-8df2-8a5f3e7488b8.png)

**Comment by team-pct** [comment]
@carlosnpz Please select on settings, Default sub

**Comment by kim0** [comment]
Well even if the default subtitle is disabled, he should still be able to
select subs .. So this is probably still a bug, right

**Comment by team-pct** [comment]
@kim0 actually it is not a bug build 35 is using OpenSub only we are testing if we can ditch Ysub

**Comment by kim0** [comment]
Yes, I don't care which provider we end up using, what I'm saying is, a
user should still be able to select subtitles on a show by show basis
without selecting a default subtitle all the time. Right

**Comment by carlosnpz** [comment]
Ok, @team-pct that worked for me! Just have to synchronize the subtitles...

**Comment by souzadenis** [comment]
I have the same problem and realized that only happens on Windows 64bit.

**Comment by raphcool12** [comment]
same thing for me no subtitles I'm windows 10 64 bits :(

**Comment by Breaking1** [comment]
Subtitles work in the latest build from here, i'm on windows 10 64bits.

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

**Comment by raphcool12** [comment]
@Breaking1  I just Install the last stable bulid form the link you gave me and still no sub :(

**Comment by Breaking1** [comment]
I have subtitles on both movies and tv show, i need to set a default in settings for tv shows.

As you can see here it works fine on movies too:

http://i.imgur.com/2WUB2iC.png?1

http://i.imgur.com/ieT5h0Q.jpg?1

**Comment by raphcool12** [comment]
@Breaking1  I see your picture but I still don't understand why it's not working for me when I download the last build erlier this week sub was working very well if I understand well the build we saw on the home page is the most stable build right? and for now it's the 32 if I'm right ,and stable mean the version who as least bug as possible right?

sorry for my bad english :)

**Comment by Breaking1** [comment]
@raphcool12   No worries about your English, i understand what you mean very well.

The one on the official site( https://popcorntime.sh/ ) is the most stable release yes, but there's nothing wrong with testing and using builds from Jenkins. They may contain some bugs since they get build every time a change in the code is made. But if you want to test the latest improvements they are really great and easy to use.

I'm using build #43: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/43/

It has working subtitles and a functional Torrent collection and magnet links i think is fixed.

Not sure why it isn't working for you, have you tried a proper uninstall(remove settings/databases) and manually check that every thing is gone and then try?

**Comment by raphcool12** [comment]
@Breaking1  yes I made a complete uninstall with revo uninstaller and even delete registery file with it But I install popcorn time on my parent laptop and no sub either

**Comment by Breaking1** [comment]
@raphcool12 try to start a movie, just because there is a x on the main page doesn't mean they aren't there. If you start a movie you will see that all the available subtitles are there, you just need to set a default subtitle in settings or chose after you start a movie like on tv shows.

I think you only find an x on the main page because they are experimenting with using Opensubtitles instead of Yify as a source for subtitles, main page will probably be fixed if they deceide to change provider permanently.

**Comment by raphcool12** [comment]
ha ha you right @Breaking1  the sub  just no show on the movie description but when you start the movie all sub is there haven my defalaut french sub is select thanks again :)

**Comment by carlosnpz** [comment]
Well... Don't know what happened, but subtitles are not showing again. I disabled Open Subtitles, the X is still appearing in the movie main page, I start it and the list finally shows, but even selecting any of the "available" languages, subtitles won't be there.

**Comment by Jonnathanjons** [comment]
Hello I have the same issue even in the latest build. Subtitle option is not showing . Can anyone please help to change any settings or backend file ?see the screenshot

![subtitle notshowiginpt](https://cloud.githubusercontent.com/assets/20332723/18543128/e5f27cce-7b4b-11e6-9b2b-3ed2c9541ec7.JPG)

**Comment by carlosnpz** [comment]
Why was it closed? Problem was not solved, yet...

**Comment by ChrisAlderson** [comment]
Moved to #227. The info in this issue won't go to waste

**Comment by cpmpub** [comment]
It has automatic subtitles search support from yify yts subtitles http://ytssubtitles.org/?
