### ISSUE TITLE
Movie Gifs Missing

### ISSUE THREAD

**Issue by vendforce** [popcorntime/popcorntime#9]
![popcorn](https://cloud.githubusercontent.com/assets/15267883/13197021/a82bb2e6-d7d8-11e5-8eb1-1f7841437505.png)

**Comment by team-pct** [comment]
Please get the last version from ci.popcorntime.sh

**Comment by vendforce** [comment]
![screenshot from 2016-02-20 19-19-31](https://cloud.githubusercontent.com/assets/15267883/13198663/eaf52458-d806-11e5-9f0a-482c35f69c78.png)

**Comment by wallydz** [comment]
I still cannot reproduce this bug , can you open console and help us more? F12

**Comment by vendforce** [comment]
Im getting a lot of these messages in console 
https://walter.trakt.us/images/movies/000/187/666/posters/medium/c2ccb26eb8.jpg Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

Ive even tried a vpn to see was my isp blocking it 
The movies play but just no movie images being shown

But when I click the link above the picture opens in my browser ??? strange !!!

**Comment by 394394394** [comment]
The Trakt API had some problems this week, could be related.

[February 15](https://twitter.com/trakt/status/699366646842961920)
[February 18](https://twitter.com/trakt/status/700405303280431104)

**Comment by 394394394** [comment]
Hey @vendforce, is this problem still happening?

**Comment by vendforce** [comment]
Yes, I dont know thats wrong ... Ive removed the /root/.config/Popcorn-Time folder and tried it still no luck, images are not showing . I've tried installing an older version etc no matter what I do the images dont show, but when I click the link to the image in console mode it opens up in my browser showing the image

So Im perplexed to what is going on , Im now just doing things to eliminate the problem , disabling firewall, clearing all caches, trying a different internt connection , using a proxy etc

**Comment by vendforce** [comment]
Ive since reinstall my operating system .. and retried popcorntime on a fresh install and its still the same, No images showing, Ive disabled firewall,rebooted and Im not using a proxy or anything that could block trakt but still no images , Is anyone else having this problem 

## EDIT :

![screenshot from 2016-02-27 15-08-13](https://cloud.githubusercontent.com/assets/15267883/13373611/45f6fb44-dd64-11e5-9900-610d5d5f6fd5.png)

Ive tried the git version and Im now getting this whats this ?? thats ugly !!!!!
I have to search for the latest films on google then enter the film in the search in poprcorntime thats too much work the layout is very ugly and not very Intuitive

**Comment by 394394394** [comment]
Are you sure you pulled from https://github.com/popcorn-official/popcorn-desktop.git?

The previous error I can confirm but this last image shouldn't exist.

**Comment by Breaking1** [comment]
@vendforce that's not from the version supported here.

As @394394394 already posted, here is where you should build from.

https://github.com/popcorn-official/popcorn-desktop.git

That's from time4popcorn and not this fork https://popcorntime.sh/

**Comment by micopiira** [comment]
Same here.

I'm running version 039267a11da9082c6a45cdb66e985c94519e3dd9 from the development branch.

![2016-02-28-201149_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5475859/13380971/2672b606-de58-11e5-9a03-e397e49bd60b.png)

**Comment by vendforce** [comment]
See it ain't just me .. other people are having problems

whether its the git version, the latest release version or the previous release Ive tried all of them
and none of them show any images

**Comment by raphcool12** [comment]
the gifs work fine for me exept when I go in my favorite section no gif appear but If I click on it I get the poster need to be fix

**Comment by raphcool12** [comment]
ok now is been fix with the build 50

**Comment by dol** [comment]
I was able to track down the issue. The currently used version of node-webkit (0.12.2), which is based of Chromium 41.0.2272.76, has some limitation in the crypto stack when using the [HTML5 img API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image).

The following [node-webkit example](https://gist.github.com/dol/10b94d07dfc29fed7dd4) is not fetching the image in nw 0.12.2, but in the current 0.13.0-rc2 (Chromium 49.0.2623.87).

I guess that between Chromium 41 and 49 this issue was fixed for Linux.
There are two ways to fix this issue:
- Replace '[new Image](https://github.com/popcorn-official/popcorn-desktop/commit/3d382e0c249d5b346956f899c185ef89883c59f8#diff-c5ffd041c71b80744fa64695418b67b4R163)' with an different implementation
- Use nw 0.13.0-rc2

**Comment by micopiira** [comment]
@team-pct stable NW.js v0.13 was released yesterday http://nwjs.io/blog/whats-new-in-0.13/, maybe it would fix this?

**Or** by looking at those GH branch names, I'm hoping you are moving to electron?

**Comment by cesaraceytuno** [comment]
Im having the same problem. Tried previous versions as well but still no luck

**Comment by Crandel** [comment]
I also have the same problem on my Arch x64.

**Comment by G-Ray** [comment]
That's stange : On one up-to-date Archlinux Desktop, posters are shown, meanwhile on an up-to-date Arch laptop, it does not work.

**Comment by PeterMX** [comment]
same problem ubuntu 16.04

**Comment by marcosfede** [comment]
any fix for this?

**Comment by aurimus** [comment]
Still not working, maybe somebody wants to compare to https://github.com/PopcornTimeCommunity/desktop ? that one is working for me

**Comment by ghost** [comment]
Downloaded the latest from Jenkins 3 minutes ago and ran on Ubuntu 14.04 64-bit. Same problem.

**Comment by VitorVRS** [comment]
I wish i could reproduce this

**Comment by vendforce** [comment]
Just because you don't have the issue doesn't mean it doesn't exist

**Comment by VitorVRS** [comment]
@vendforce I know that, but i want to solve this. 
This issue is open a thousand years and i dont have an good environment to try reproduce. :ok_hand:

**Comment by vendforce** [comment]
#VitorVRS YOU DICK 
thousand years ? arsehole !!!

I've installed a fresh install of arch and still no images many people are having the same problem
if you are not having this problem then fuck off and dont post that yu aren't you fucking idiot

**Comment by VitorVRS** [comment]
@vendforce sorry if you have been offended. I'll ignore your comment above and move on.
Thank you.

**Comment by vendforce** [comment]
holy shit !!! i'M DUMBFOUNDED !!! 

SORRY BUT offended is for idiots I'm upset that there is people around like you 

being offended is an amerian thing

**Comment by vendforce** [comment]
>I wish i could reproduce this

# I wish you could grow a brain

**Comment by vendforce** [comment]
You got burned for being an arsehole !!!

why waste yout time logging in and commenting "you wish you could repoduce this "

there is lots of people having this problem !!! why do you wish you could ?? maybe becuase your an arsehole that wants to have a bug ???

**Comment by vendforce** [comment]
### AND JUST TO POINT OUT THE FACT !!! 
you quoted yu wanted to solve this !!! if your not having the issue why are you here commenting ??

**Comment by vendforce** [comment]
Kiss kiss xx love you lots VitorVTS

**Comment by vendforce** [comment]
### This issue is open a thousand years and i dont have an good environment to try reproduce.

IS LIKE SAYING wy is father chritsmas sack so big ?

because he only comes once a year

**Comment by vendforce** [comment]
### AND THE DICKHEAD A YEAR  AWARD OF 2016 GOES TO ......... VitorVTS

**Comment by aurimus** [comment]
Jesus, is there a way to delete the comments above? It's total waste of topic. 

It is however sad that I have to rely on much less supported version,namely Community Edition, and commit to it (my pull requests in CE edition [hasn't been accepted for weeks](https://github.com/PopcornTimeCommunity/desktop/pulls)), just because this has some kind of weird issue that a billion people is having also. 

I'm seeing the same thing as @micopiira

![ptsh_https_issue](https://cloud.githubusercontent.com/assets/1052992/14907961/6135d994-0dd8-11e6-8fcf-edd81ed66bc7.png)

Does CE version and this use the same API? **update:** CE is using different API, namely YTS
![ptce_no_problemo](https://cloud.githubusercontent.com/assets/1052992/14908005/236d6fe0-0dd9-11e6-93d9-5578bc77ba7c.png)

**Comment by aurimus** [comment]
![ptsh_https_issue](https://cloud.githubusercontent.com/assets/1052992/14907961/6135d994-0dd8-11e6-8fcf-edd81ed66bc7.png)

**Comment by aurimus** [comment]
There's same exact poster on http protocol, why is https is even used here?

https://walter.trakt.us/images/movies/000/223/804/posters/medium/fbe7f827f6.jpg
http://walter.trakt.us/images/movies/000/223/804/posters/medium/fbe7f827f6.jpg

**Comment by micopiira** [comment]
@aurimus I see absolutely no reason not to use https in 2016, and this should be fixed.

Please see http://webmasters.stackexchange.com/a/15606

**Comment by team-pct** [comment]
@vendforce  it is sad to see that you are insulting a guy ( who by the way have no affiliation with Popcorn Time ) in the same time it is sad , so let me repeat THIS IS A FREE , Open Source , Community Project if you wanna fix this issue you are all welcome to PR !

**Comment by G-Ray** [comment]
Please see https://github.com/popcorn-official/popcorn-desktop/issues/49

Updating to nw 0.13.x would resolve this. Not a difficult task, but the only thing is that we have to rebuild nw with more codecs as stated on the upstream repo https://github.com/butterproject/butter-desktop/issues/339

**Comment by team-pct** [comment]
@G-Ray we are working on that , if it is taking time , please read more on blog.popcorntime.sh , Thank you
